# Generated by Django 4.2.16 on 2025-09-05 18:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('summary', models.TextField(help_text='Brief description for listings', max_length=500)),
                ('description', ckeditor.fields.RichTextField(help_text='Detailed service description')),
                ('base_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_note', models.CharField(blank=True, help_text="e.g., 'Starting from' or 'Per unit'", max_length=200)),
                ('duration_estimate', models.CharField(blank=True, choices=[('1-2', '1-2 hours'), ('2-4', '2-4 hours'), ('4-8', '4-8 hours'), ('1-day', '1 day'), ('2-3-days', '2-3 days'), ('1-week', '1 week'), ('custom', 'Custom duration')], max_length=20)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Technical specifications as JSON')),
                ('features', models.TextField(blank=True, help_text='Key features, one per line')),
                ('requirements', models.TextField(blank=True, help_text='Requirements or prerequisites')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-is_featured', 'category__order', 'name'],
            },
        ),
    ]
