# Generated by Django 4.2.16 on 2025-09-03 14:42

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', ckeditor.fields.RichTextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('services', 'Services'), ('pricing', 'Pricing'), ('maintenance', 'Maintenance'), ('installation', 'Installation'), ('repair', 'Repair')], default='general', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Global Cool-Light E.A LTD', max_length=200)),
                ('tagline', models.CharField(default='Your Trusted HVAC Partner', max_length=200)),
                ('description', ckeditor.fields.RichTextField(default='Professional HVAC services in Kenya. We specialize in air conditioning installation, maintenance, and repair services.')),
                ('phone', models.CharField(default='+254 700 000 000', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(default='info@globalcool-light.com', max_length=254)),
                ('address', models.TextField(default='Nairobi, Kenya')),
                ('working_hours', models.CharField(default='Mon-Fri: 8AM-6PM, Sat: 9AM-4PM', max_length=200)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('meta_title', models.CharField(default='Global Cool-Light E.A LTD - Your Trusted HVAC Partner', max_length=60)),
                ('meta_description', models.CharField(default='Professional HVAC services in Kenya. Installation, maintenance, and repair of air conditioning systems.', max_length=160)),
                ('meta_keywords', models.CharField(default='HVAC, air conditioning, cooling, heating, Kenya, Nairobi', max_length=200)),
                ('google_analytics_id', models.CharField(blank=True, max_length=20, null=True)),
                ('google_maps_api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', ckeditor.fields.RichTextField(blank=True, default="We're currently performing scheduled maintenance. Please check back soon!")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
    ]
