# Generated by Django 4.2.16 on 2025-09-07 01:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout', models.PositiveIntegerField(default=3600, help_text='Session timeout in seconds (default: 3600 = 1 hour)')),
                ('remember_me_duration', models.PositiveIntegerField(default=1209600, help_text='Remember me duration in seconds (default: 1209600 = 2 weeks)')),
                ('max_login_attempts', models.PositiveIntegerField(default=5, help_text='Maximum failed login attempts before account lockout')),
                ('lockout_duration', models.PositiveIntegerField(default=900, help_text='Account lockout duration in seconds (default: 900 = 15 minutes)')),
                ('password_min_length', models.PositiveIntegerField(default=8)),
                ('password_require_uppercase', models.BooleanField(default=True)),
                ('password_require_lowercase', models.BooleanField(default=True)),
                ('password_require_numbers', models.BooleanField(default=True)),
                ('password_require_symbols', models.BooleanField(default=False)),
                ('password_expiry_days', models.PositiveIntegerField(default=0, help_text='Password expiry in days (0 = never expires)')),
                ('enable_2fa', models.BooleanField(default=False)),
                ('force_2fa_for_admins', models.BooleanField(default=False)),
                ('enable_ip_whitelist', models.BooleanField(default=False)),
                ('allowed_ips', models.TextField(blank=True, help_text='Comma-separated list of allowed IP addresses')),
                ('log_login_attempts', models.BooleanField(default=True)),
                ('log_admin_actions', models.BooleanField(default=True)),
                ('log_retention_days', models.PositiveIntegerField(default=90, help_text='Number of days to retain security logs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('booking_reminder', 'Booking Reminder'), ('quotation_sent', 'Quotation Sent'), ('quotation_accepted', 'Quotation Accepted'), ('quotation_rejected', 'Quotation Rejected'), ('service_completed', 'Service Completed'), ('payment_reminder', 'Payment Reminder'), ('welcome_email', 'Welcome Email'), ('password_reset', 'Password Reset'), ('general_notification', 'General Notification')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField(help_text='Use {{variable_name}} for dynamic content')),
                ('available_variables', models.TextField(blank=True, help_text='JSON list of available variables for this template')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
                'unique_together': {('template_type', 'is_default')},
            },
        ),
    ]
