# Generated by Django 4.2.16 on 2025-09-07 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0002_client_inquiry_quotation_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Admin user assigned to this chat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
